on:
    workflow_dispatch: {}
    push:
        branches:
            - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

        - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 📂 Sync files
        uses: Penguibird/FTP-Deploy-Action@4.2.0
        with:
          server: ftp.tunzitsolutions.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: http://dev.hinvites.com/
